<!--
/**
 * Naxero.com
 * Professional ecommerce integrations for Magento
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Naxero
 * @author    Platforms Development Team <contact@naxero.com>
 * @copyright Naxero.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://www.naxero.com
 */
-->

<?php
// Get the module settings
$settings = $block->helper->getConfigValues();
?>

<div id="translation-container" class="files-view">
	<div id="translation-table-list">
		<div id="translation-table-toolbar">
			<!--
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-group-filter">
					<span><?= __('Group'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?= $block->helper->getFilterSelect([
			            'id' => 'translation-group-filter',
			            'name' => 'translation-group-filter',
			            'class' => 'admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			-->
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-type-filter">
					<span><?= __('Type'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?= $block->helper->getFilterSelect([
			            'id' => 'translation-type-filter',
			            'name' => 'translation-type-filter',
			            'class' => 'admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-locale-filter">
					<span><?= __('Locale'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?= $block->helper->getFilterSelect([
			           'id' => 'translation-locale-filter',
			           'name' => 'translation-locale-filter',
			           'class' => 'admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="admin__form-field">
				<label class="label admin__form-field-label">
					<span><?= __('Pagination'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?= $block->helper->getPagerSelect([
			            'name' => 'translation-paging-filter',
			            'class' => 'admin__control-select translation-paging-filter'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
				<div class="page-actions-inner">
					<div class="page-actions-buttons">
						<?php if ($settings['allow_file_creation'] == '1'): ?>
							<button id="new-file" name="new-file" type="button" class="action-default primary">
								<span><?= __('New file'); ?></span>
							</button>
						<?php endif; ?>
						<button id="update-files" name="update-files" type="button" class="action-default primary">
							<span><?= __('Scan files'); ?></span>
						</button>
						<button id="flush-cache-list" name="flush-cache-list" type="button" class="action- scalable action-secondary">
							<span><?= __('Flush cache'); ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>
		<div id="translation-table-content"></div>
	</div>
	<div id="translation-table-detail">
		<div id="translation-detail-toolbar">
			<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
				<div class="page-actions-inner">
					<div class="page-actions-buttons">
						<button id="button-back" name="button-back" type="button" class="action- scalable back">
							<span><?= __('Back'); ?></span>
						</button>
						<button id="add-row" name="add-row" type="button" class="action- scalable action-primary">
							<span><?= __('Add row'); ?></span>
						</button>
						<button id="import-data" name="import-data" type="button" class="action- scalable action-primary">
							<span><?= __('Import data'); ?></span>
						</button>
						<button id="download-file" name="download-file" type="button" class="action- scalable action-primary">
							<span><?= __('Download file'); ?></span>
						</button>
						<button id="flush-cache-detail" name="flush-cache-detail" type="button" class="action- scalable action-secondary">
							<span><?= __('Flush cache'); ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>	
		<div id="translation-file-path"></div>	
		<div class="admin__form-field">
			<label class="label admin__form-field-label">
				<span><?= __('Pagination'); ?></span>
			</label>
			<div class="admin__form-field-control">
				<?= $block->helper->getPagerSelect([
					'name' => 'translation-paging-filter',
					'class' => 'admin__control-select translation-paging-filter'
				], $block->getLayout()); ?>	
			</div>
		</div>
		<div id="translation-table-detail-content"></div>
	</div>
</div>

<div data-mage-init='{
	"filesjs": {
		"dataUrl": "<?= $block->getUrl('translation/data/index', ['view' => 'files']); ?>",
		"scanUrl": "<?= $block->getUrl('translation/scan/index'); ?>",
		"detailViewUrl": "<?= $block->getUrl('translation/files/detail'); ?>",
		"cacheUrl": "<?= $block->getUrl('translation/cache/index'); ?>",
		"promptUrl": "<?= $block->getUrl('translation/blocks/index'); ?>",
		"newFileUrl": "<?= $block->getUrl('translation/files/create'); ?>",
		"localeData": "<?= $block->helper->getTableLocaleData(); ?>",
		"settings": <?= json_encode($settings); ?>
	}
}'>
