<div id="translation-container">
	<div id="translation-table-list">
		<div id="translation-table-toolbar">
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-group-filter">
					<span><?php echo __('Group'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?php echo $block->helper->getSelect([
			            'id' => 'translation-group-filter',
			            'name' => 'translation-group-filter',
			            'class' => 'select admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-type-filter">
					<span><?php echo __('Type'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?php echo $block->helper->getSelect([
			            'id' => 'translation-type-filter',
			            'name' => 'translation-type-filter',
			            'class' => 'select admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-locale-filter">
					<span><?php echo __('Locale'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?php echo $block->helper->getSelect([
			           'id' => 'translation-locale-filter',
			           'name' => 'translation-locale-filter',
			           'class' => 'select admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			
			<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
				<div class="page-actions-inner">
					<div class="page-actions-buttons">
						<button id="update-files" name="update-files" type="button" class="action-default primary">
							<span><?php echo __('Scan files'); ?></span>
						</button>
						<button id="flush-cache-list" name="flush-cache-list" type="button" class="action-default primary">
							<span><?php echo __('Flush cache'); ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>
		<div class="translation-pagination"></div>
		<div id="translation-table-content"></div>
		<div class="translation-pagination"></div>
	</div>
	<div id="translation-table-detail">
		<div id="translation-detail-toolbar">
			<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
				<div class="page-actions-inner">
					<div class="page-actions-buttons">
						<button id="button-back" name="button-back" type="button" class="action- scalable back">
							<span><?php echo __('Back'); ?></span>
						</button>
						<button id="download-file" name="download-file" type="button" class="action- scalable action-secondary">
							<span><?php echo __('Download CSV'); ?></span>
						</button>
						<button id="flush-cache-detail" name="flush-cache-detail" type="button" class="action-default primary">
							<span><?php echo __('Flush cache'); ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>	
		<div id="translation-file-path"></div>	
		<div class="translation-pagination"></div>
		<div id="translation-table-detail-content"></div>
		<div class="translation-pagination"></div>
	</div>
</div>

<div data-mage-init='{"filesjs":{"targetLocale": "<?php echo $block->helper->getUserLanguage(); ?>", "dataUrl": "<?php echo $block->getUrl('translation/data/index', ['view' => 'files']); ?>", "scanUrl": "<?php echo $block->getUrl('translation/scan/index'); ?>", "detailViewUrl": "<?php echo $block->getUrl('translation/files/detail'); ?>", "cacheUrl": "<?php echo $block->getUrl('translation/cache/index'); ?>"}}'>
