<div id="translation-container">
	<div id="translation-table-list">
		<div id="translation-table-toolbar">
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-group-filter">
					<span><?= __('Group'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?= $block->helper->getSelect([
			            'id' => 'translation-group-filter',
			            'name' => 'translation-group-filter',
			            'class' => 'select admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-type-filter">
					<span><?= __('Type'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?= $block->helper->getSelect([
			            'id' => 'translation-type-filter',
			            'name' => 'translation-type-filter',
			            'class' => 'select admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="admin__form-field">
				<label class="label admin__form-field-label" for="translation-locale-filter">
					<span><?= __('Locale'); ?></span>
				</label>
				<div class="admin__form-field-control">
					<?= $block->helper->getSelect([
			           'id' => 'translation-locale-filter',
			           'name' => 'translation-locale-filter',
			           'class' => 'select admin__control-select'
			    	], $block->getLayout()); ?>	
				</div>
			</div>
			<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
				<div class="page-actions-inner">
					<div class="page-actions-buttons">
						<button id="update-files" name="update-files" type="button" class="action-default primary">
							<span><?= __('Scan files'); ?></span>
						</button>
						<button id="flush-cache" name="flush-cache" type="button" class="action-default primary">
							<span><?= __('Flush cache'); ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>
		<div id="translation-table-content"></div>
	</div>
</div>

<div data-mage-init='{"stringsjs":{"targetLocale": "<?= $block->helper->getUserLanguage(); ?>", "dataUrl": "<?= $block->getUrl('translation/data/index', ['view' => 'strings']); ?>", "scanUrl": "<?= $block->getUrl('translation/scan/index'); ?>", "detailViewUrl": "<?= $block->getUrl('translation/files/detail'); ?>", "cacheUrl": "<?= $block->getUrl('translation/cache/index'); ?>"}}'>
