<div id="translation-container">
	<div id="translation-table-list">
		<div id="translation-table-toolbar">		
			<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
				<div class="page-actions-inner">
					<div class="page-actions-buttons">
						<button id="update-files" name="update-files" type="button" class="action-default primary">
							<span><?= __('Scan files'); ?></span>
						</button>
						<button id="clear-logs" name="clear-logs" type="button" class="action-default primary">
							<span><?= __('Clear logs'); ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>	
		<div id="translation-table-content"></div>
	</div>
	<div id="translation-table-detail">
		<div id="translation-detail-toolbar">
			<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
				<div class="page-actions-inner">
					<div class="page-actions-buttons">
						<button id="button-back" name="button-back" type="button" class="action- scalable back">
							<span><?= __('Back'); ?></span>
						</button>
						<button id="download-file" name="download-file" type="button" class="action- scalable action-secondary">
							<span><?= __('Download CSV'); ?></span>
						</button>
						<button id="flush-cache-detail" name="flush-cache-detail" type="button" class="action-default primary">
							<span><?= __('Flush cache'); ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>	
		<div id="translation-file-path"></div>	
		<div id="translation-table-detail-content"></div>
	</div>
</div>

<div data-mage-init='{"logsjs":{"targetLocale": "<?= $block->helper->getUserLanguage(); ?>", "dataUrl": "<?= $block->getUrl('translation/data/index', ['view' => 'logs']); ?>", "scanUrl": "<?= $block->getUrl('translation/scan/index', ['view' => 'logs']); ?>", "clearLogsUrl": "<?= $block->getUrl('translation/logs/index', ['action' => 'clear_logs']); ?>", "detailViewUrl": "<?= $block->getUrl('translation/files/detail'); ?>", "cacheUrl": "<?= $block->getUrl('translation/cache/index'); ?>"}}'>
