<div id="translation-container">
	<div id="translation-table-list">	
		<div id="translation-table-content"></div>
	</div>
</div>

<div data-mage-init='{"logsjs":{"targetLocale": "<?php echo $block->getUserLanguage(); ?>", "dataUrl": "<?php echo $block->getUrl('translation/data/index', ['view' => 'strings']); ?>", "scanUrl": "<?php echo $block->getUrl('translation/scan/index'); ?>", "detailViewUrl": "<?php echo $block->getUrl('translation/files/detail'); ?>", "cacheUrl": "<?php echo $block->getUrl('translation/cache/index'); ?>"}}'>
