<div class="admin__form-field">
	<fieldset class="admin__form-field">
		<strong><?php echo __('Filters'); ?></strong>
	</fieldset>
	<label class="label admin__form-field-label" for="translation-group-filter">
		<span><?php echo __('Group'); ?></span>
	</label>
	<div class="admin__form-field-control">
		<?php echo $block->getSelect([
            'id' => 'translation-group-filter',
            'name' => 'translation-group-filter',
            'class' => 'select admin__control-select'
    	]); ?>	
	</div>
	<label class="label admin__form-field-label" for="translation-locale-filter">
		<span><?php echo __('Locale'); ?></span>
	</label>
	<div class="admin__form-field-control">
		<?php echo $block->getSelect([
           'id' => 'translation-locale-filter',
           'name' => 'translation-locale-filter',
           'class' => 'select admin__control-select'
    	]); ?>	
	</div>

</div>